services:
  nestjs:
    build: ../
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - ../.env.docker    
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: articles_postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: